"""
A scalar that can represent any JSON value.
"""
scalar JSON

union RosterDelta = RosterReset | RosterUpsert | RosterRemove

type RosterQuery {
	person(id: UUID!): RosterView
}

type RosterRemove {
	revision: Int!
	projector: String!
	key: JSON!
	cause: JSON
}

type RosterReset {
	revision: Int!
	views: [RosterViewUnion!]!
}

type RosterSubscription {
	rosterDeltas: RosterDelta!
}

type RosterUpsert {
	revision: Int!
	view: RosterViewUnion!
	cause: JSON
}

type RosterView {
	userId: UUID!
	email: String!
	displayName: String!
}

union RosterViewUnion = RosterView

"""
A UUID is a unique 128-bit number, stored as 16 octets. UUIDs are parsed as
Strings within GraphQL. UUIDs are used to assign unique identifiers to
entities without requiring a central allocating authority.

# References

* [Wikipedia: Universally Unique Identifier](http://en.wikipedia.org/wiki/Universally_unique_identifier)
* [RFC4122: A Universally Unique Identifier (UUID) URN Namespace](http://tools.ietf.org/html/rfc4122)
"""
scalar UUID

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
schema {
	query: RosterQuery
	subscription: RosterSubscription
}
