scalar Affordances

union BoardDelta = BoardReset | BoardUpsert | BoardRemove

type BoardMutation {
	createBoard(id: UUID!, name: String!, isPublic: Boolean!): MutationAck!
	archiveBoard(id: UUID!): MutationAck!
	mintBoardInvite(id: UUID!): String!
	setBoardMembership(boardId: UUID!, userId: UUID!, member: Boolean!): MutationAck!
}

type BoardQuery {
	board(id: UUID!): BoardView
	boards: [BoardView!]!
	orgBoards: [BoardView!]!
}

type BoardRemove {
	revision: Int!
	projector: String!
	key: JSON!
	cause: JSON
}

type BoardReset {
	revision: Int!
	views: [BoardViewUnion!]!
}

type BoardSubscription {
	boardDeltas: BoardDelta!
	orgBoardDeltas: OrgBoardDelta!
}

type BoardUpsert {
	revision: Int!
	view: BoardViewUnion!
	cause: JSON
}

type BoardView {
	id: UUID!
	name: String!
	isPublic: Boolean!
	archived: Boolean!
	affordances: Affordances!
}

union BoardViewUnion = BoardView

"""
A scalar that can represent any JSON value.
"""
scalar JSON

type MutationAck {
	success: Boolean!
}

union OrgBoardDelta = OrgBoardReset | OrgBoardUpsert | OrgBoardRemove

type OrgBoardRemove {
	revision: Int!
	projector: String!
	key: JSON!
	cause: JSON
}

type OrgBoardReset {
	revision: Int!
	views: [OrgBoardViewUnion!]!
}

type OrgBoardUpsert {
	revision: Int!
	view: OrgBoardViewUnion!
	cause: JSON
}

union OrgBoardViewUnion = BoardView

"""
A UUID is a unique 128-bit number, stored as 16 octets. UUIDs are parsed as
Strings within GraphQL. UUIDs are used to assign unique identifiers to
entities without requiring a central allocating authority.

# References

* [Wikipedia: Universally Unique Identifier](http://en.wikipedia.org/wiki/Universally_unique_identifier)
* [RFC4122: A Universally Unique Identifier (UUID) URN Namespace](http://tools.ietf.org/html/rfc4122)
"""
scalar UUID

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
schema {
	query: BoardQuery
	mutation: BoardMutation
	subscription: BoardSubscription
}
